[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = "let g:ale_fixers={'ruby':['rubocop'],}"

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo  = 'preservim/nerdtree'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
